### ISSUE TITLE
[0.90] Can't move, recycle or destroy files and folders

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#288] opened 2020-06-18 20:35 UTC
Title says all. Create folders and files, then try to move files in folders, put in recycle bin or destroy them. Confirmation dialogs appears but nothing happens.

**Comment by trunkmaster** [comment] 2020-06-22 00:38
@zeroheure Works for me. Please provide more detailed use case.

**Comment by Bruwhizz** [comment] 2020-06-26 17:07
@trunkmaster I have the same issue. Fedora 31, NextSpace 0.90, AMD CPU. It doesn't perform the action but it does display the label i.e "copying...", and I can't close the task from the process viewer. It also prevents me from logging out so I need to turn my whole computer on and off again. Also, while the issue is currently on Fedora for me I have experienced it on CentOS 7 & 8.

**Comment by trunkmaster** [comment] 2020-06-26 23:44
@Bruwhizz I need exact list of steps you've made. For example:
1. Install NextSpace with nextspace_install.sh
2. Start login panel with command...
3. Logged in with user...
4. Created folder named...
5. Opened window...
6. Created file...
7. Made copy from ... to ...

Otherwise, I can't reproduce problem to get it fixed.

**Comment by zeroheure** [comment] 2020-06-27 09:50
Here's my general install process :

1. use of QEMU/KVM through libvirt
1. install Centos 7 minimal, french localization, keyboard variant is fr-bepo
1. yum update
1. yum install epel-release
1. yum update
1. yum install nano
1. copy NextSpace tarball
1. setup NextSpace with nextspace_install.sh
1. start login panel with nextspace_install.sh last step
1. login with user created by  nextspace_install.sh
1. logout
1. fix known issues #276
1. reboot

**Comment by zeroheure** [comment] 2020-06-27 10:14
if I do simple tests now, it works well only on one of my two virtual machines.

1. workspace in browse mode
1. create folder named "New folder"
1 duplicate file "underscore" to "CopyOf_underscore"
1. switch to view mode
1. move "CopyOf_underscore" in "New folder"
1. move "CopyOf_underscore" in trash
1. move "New folder"  in trash
1. restore

1. Workspace in view mode
1. same steps except 4

To resume : 

- works well on my first VM, doesn't work on my second one.
- sometimes it can't restore "CopyOf_underscore" on my first VM

I will fully reinstall on a third new VM, carefuly note steps and test again all my issues.

**Comment by zeroheure** [comment] 2020-06-28 13:26
On a new VM, problem happens only on first working login (issue #276 fixed). Works like a charm after reboot. But there is more than recycle problems : any file operation failed at first login. 

### Test operations
#### Recycler
1. create new folder "NewFolder"
    - switch to icon mode
    - move NewFolder onto Recycler icon
    - window open asking to confirm
    - confirm
    - nothing happens
1.create new TextEdit document
    - save in ~/
    - move onto Recycler icon
    - window open asking to confirm
    - confirm
    - nothing happens
1. create new TextEdit document
    - save in ~/NewFolder
    - move doc onto Recycler icon
    - window open asking to confirm
    - confirm
    - nothing happens
1. repeat operations
    - new folders and documents
    - move onto Recycler icon
    - etc. 
    - nothing happens.

#### Others
1. Destroy
    - Try to destroy previously created docs and folders
    - window open asking to confirm
    - confirm
    - nothing happens
1. Duplicate, compress, cut, copy, paste
    - Try to ... previously created docs and folders
    - nothing happens
1. Graphical move
    - Try to move some files into folder
    - folder icon open
    - nothing happens

### Logout
- Workpace is still working (90% of cpu time)
- When closing Terminal, Workspace menu doesn't reappear 
- Need to hard kill workspace proces to close session

**Comment by zeroheure** [comment] 2020-06-30 08:54
Problem happens again, on the same account amd VM. I tried several behaviour (logout, reboot, cleaning workspace state, etc.), it allways happens.

**Comment by Bruwhizz** [comment] 2020-07-02 05:52
I experienced the behavior on a bare hardware install (yes yes I know that's a bad idea but why not) and the specific actions were as follows:

1. Install Fedora 31 with minimal
(I also experienced it with CentOS & RHEL 7 & 8)
2. Download & Install without developer options enabled
3. Run LoginWindow
4. Log in
5. Then I tried making the files, etc.
     5.1. I made a new folder with the GUI, didn't change the name and it got stuck trying to move, copy, or delete it.
     5.2. I made a new folder with the GUI, renamed it to "Test_Folder" and it got stuck trying to move, copy, or delete it.
     5.3. Downloaded a tarball with Firefox, successfully extracted it, but it got stuck again trying to move, copy, and delete it.
6. I reinstalled with developer options enabled and experienced the same results.

I dunno if this helps at all but those are the steps I took. Note that it was on bare metal with an AMD Ryzen CPU

**Comment by trunkmaster** [comment] 2020-07-14 11:14
@zeroheure @Bruwhizz nextspace_install.sh disables SELinux. To apply this change Linux you have to reboot. I guess reboot event neded before RPMs install. Need to check...

**Comment by zeroheure** [comment] 2020-07-14 15:54
1. it happens at random times, not only after install.
2. I confirm it is only in Icon view mode.

**Comment by trunkmaster** [comment] 2020-07-14 16:18
@zeroheure what do you mean by "nothing happens" - File Viewer in Icon mode is not updated? Does Recycler contains moved folder? Does parent folder still contains removed folder (click on parent folder in Path View)?

**Comment by zeroheure** [comment] 2020-07-15 16:55
@trunkmaster Better than words here's a short record on Centos 7 with your original packages.
![trash](https://user-images.githubusercontent.com/24126/87572956-92fe7880-c6cc-11ea-9111-a66f9f5e641d.gif)

**Comment by trunkmaster** [comment] 2020-07-16 10:27
@zeroheure I suppose something wrong with with FileMover operations. Mark this as bug.

**Comment by trunkmaster** [comment] 2021-11-28 18:17
Hi @zeroheure, closing issues. Feel free to reopen it when you'll have possibility to make testing.

**Closed by trunkmaster** 2021-11-28 18:17 UTC
Labels: bug

**Comment by zeroheure** [comment] 2022-02-21 12:09
Seems to work now with current Master branch.
