### ISSUE TITLE
Build and Install Fails - Centos 7 Minimal

### ISSUE THREAD

**Issue by markusmeyerhofer** [trunkmaster/nextspace#30] opened 2018-09-18 21:22 UTC
Hello! I followed the build and install guide in the Wiki and stumbled upon some issues; ultimately, installation finally failed. 

Here's what I did:
Precautions: 
Installed Centos 7 (x86_64) minimal installation.
Followed the instructions as given in the Wiki.
Skipped step 2.5 for 3.5

Solvable issues:
On the Centos standard installation the following tools are missing (and can be installed using yum):

- patch
- gnustep-make
- libjpeg-devel
- libtiff-devel
- gcc-objc

Issues I have not been able to solve: 
make (step 3.5) fails: 
_Functions.m:30:41: fatal error: Foundation/NSAutoreleasePool.h: no such file or directory_

indeed the file is missing. 

Subsequently reverting to step 2.5 I encountered the following issue:
Installation fails:
_Error: nextspace-gnustep conflicts with gnustep-filesystem-2.7.0-1.3l7.x86_64_

Thank you for your good work

**Comment by trunkmaster** [comment] 2018-09-18 22:01
Thank you. Yes, you are right. Wiki page has errors. I'll  fix it. 
Some comments:
- actually 2.5 step should not be skipped, rather step 3.5 should be executed after 2.5 to install required packages.
- patch - you're right, I'll add instruction to step 3.5;
- gnustep-make - you don't need to install gnustep-make from CentOS repository (at least for now). Please install `nextspace-core-devel` - it contains all necessary Makefiles; 
- NEXTSPACE doesn't use gcc-objc - clang, llvm and libobjc2 are enough;
- libjpeg-devel, libtiff-devel - you're right it's the required packages to build GNUstep libraries. All necessary packages can be installed with command (I'll add this to Wiki) from nextspace cloned sources:
    yum install \`grep "BuildRequires" Libraries/gnustep/nextspace-gnustep.spec | awk -c '{print $2}'\`

Remained build issue is due to the lack of Foundation (gnustep-base) makefiles. Install packages described in step 2.5 and try to execute step 3.5 again.

**Comment by trunkmaster** [comment] 2018-09-18 22:34
I've made necessary edits to Wiki page in steps 2.5 and 3.5. I hope it will help you to resolve issues.

**Comment by markusmeyerhofer** [comment] 2018-09-18 22:49
Thanks so far. I reinstalled from scratch, still stuck at the configure step though:

_configure: error: You must have the gnustep-make package installed and set up the GNUSTEP_MAKEFILES environment variable to contain the path to the makefiles directory before configuring!_

Installing the gnustep-make package, however, fails due to conflicting packages:
_Error: nextspace-gnustep conflicts with gnustep-filesystem-2.7.0-1.el7.x86_64_

So the install error mentioned in my original post stems from gnustep-make conflicting. Any idea how to circumvent the mentioned configure error?

**Comment by trunkmaster** [comment] 2018-09-18 23:27
Good luck! I hope this turn will be successful.

**Comment by trunkmaster** [comment] 2018-09-20 07:38
It's seems you have broken installation. Show me your `ls -l /Library/Fonts`.

**Comment by markusmeyerhofer** [comment] 2018-09-20 11:59
You are right. There is no Fonts dir in /Library. Strange. Its a fresh install

**Comment by trunkmaster** [comment] 2018-09-20 13:27
It's not quite tested. Now I'm in active development. I plan to check it later after feature implementation phase for core applications will be completed. For now just create link `ln -s /usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Fonts /Library/Fonts`.

**Comment by markusmeyerhofer** [comment] 2018-09-20 16:32
Not sure what's going on here. Its still crashing. Just once, the error message hints the Fonts have been found:
_
● loginwindow.service - NEXTSPACE Login Panel
   Loaded: loaded (/usr/NextSpace/Apps/Login.app/Resources/loginwindow.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Thu 2018-09-20 18:24:58 CEST; 18s ago
  Process: 1058 ExecStartPost=/bin/bash -c TERM=linux /usr/bin/clear > /dev/tty1 (code=exited, status=0/SUCCESS)
  Process: 1057 ExecStart=/usr/NextSpace/Apps/Login.app/Login (code=killed, signal=SEGV)
 Main PID: 1057 (code=killed, signal=SEGV)

Sep 20 18:24:58 localhost.localdomain Login[1057]: 2018-09-20 19:24:58.756 Login[1057:1057] The font specified for NSUserFont, Helvet... found.
Sep 20 18:24:58 localhost.localdomain Login[1057]: 2018-09-20 19:24:58.756 Login[1057:1057] XGFont: selected font: Helvetica at 12.00...ilable.
Sep 20 18:24:58 localhost.localdomain Login[1057]: 2018-09-20 19:24:58.757 Login[1057:1057] XGFont: selected font: Helvetica at 12.00...ilable.
Sep 20 18:24:58 localhost.localdomain Login[1057]: 2018-09-20 19:24:58.757 Login[1057:1057] XGFont: selected font: Helvetica at 12.00...ilable.
Sep 20 18:24:58 localhost.localdomain Login[1057]: 2018-09-20 19:24:58.757 Login[1057:1057] XGFont: selected font: Courier at 12.0000...ilable.
Sep 20 18:24:58 localhost.localdomain Login[1057]: 2018-09-20 19:24:58.757 Login[1057:1057] XGFont: selected font: Fixed at 12.000000...ilable.
Sep 20 18:24:58 localhost.localdomain systemd[1]: loginwindow.service: main process exited, code=killed, status=11/SEGV
Sep 20 18:24:58 localhost.localdomain systemd[1]: Unit loginwindow.service entered failed state.
Sep 20 18:24:58 localhost.localdomain systemd[1]: Triggering OnFailure= dependencies of loginwindow.service.
Sep 20 18:24:58 localhost.localdomain systemd[1]: loginwindow.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@localhost max]# systemctl -l status loginwindow
● loginwindow.service - NEXTSPACE Login Panel
   Loaded: loaded (/usr/NextSpace/Apps/Login.app/Resources/loginwindow.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Thu 2018-09-20 18:24:58 CEST; 1min 21s ago
  Process: 1058 ExecStartPost=/bin/bash -c TERM=linux /usr/bin/clear > /dev/tty1 (code=exited, status=0/SUCCESS)
  Process: 1057 ExecStart=/usr/NextSpace/Apps/Login.app/Login (code=killed, signal=SEGV)
 Main PID: 1057 (code=killed, signal=SEGV)_

Thereafter, the error message is as it's been before. Puzzling

**Comment by markusmeyerhofer** [comment] 2018-09-20 19:16
Update: reinstalled from scratch, same result

**Comment by trunkmaster** [comment] 2018-09-20 20:31
Check if `gdomap` is service running.

**Comment by markusmeyerhofer** [comment] 2018-09-20 22:32
Yes, even when /Library/Fonts is present the error appears (it seems not to find the font, though). And yes, the gdomap is up and running

**Comment by trunkmaster** [comment] 2018-09-20 22:37
OK, check if `/usr/NextSpace/Fonts` is a link to `/usr/NextSpace/Frameworks/NXAppKit.framework/Versions/Current/Resources/Fonts` then.

**Comment by markusmeyerhofer** [comment] 2018-09-20 22:40
Yes, it is. 

I just realized that netconsole module is not loaded. Not sure if it has anything to do with the problem, but it's not as it's supposed to be. Investigating...

**Comment by trunkmaster** [comment] 2018-09-20 23:06
I know! Check if /root directory contains Library/Preferences/NSGlobalDomain.plist. If not (I' sure it doesn't) copy System/etc/skel/Library (inside cloned git repo) into /root.

**Comment by markusmeyerhofer** [comment] 2018-09-20 23:10
Well.. no, the .plist was present. Tried to replace by the one you mentioned, no change

**Comment by trunkmaster** [comment] 2018-09-20 23:17
What `defaults read NSGlobalDomain GSBackend` as root outputs?

**Comment by markusmeyerhofer** [comment] 2018-09-20 23:18
NSGlobalDomain GSBackend art

**Comment by trunkmaster** [comment] 2018-09-20 23:18
Correct. And `systemctl restart loginwindow` shows the same errors?

**Comment by markusmeyerhofer** [comment] 2018-09-20 23:21
Yes. I suspect the problem ultimately has something to do with services not able to start. netconsole (upon which I understand several services depend) fails to start as well. Apparently due to a problem with a kernel module:

_Initializing netconsole modprobe: ERROR: could not insert 'netconsole': Operation not permitted_

No idea why...

**Comment by trunkmaster** [comment] 2018-09-20 23:30
Log messages which contain "XGFont" points to the fact that GNUstep try to use "xlib" backend. NSGLobalDomain contains correct value "art". Could you try to run "/usr/NextSpace/Login.app/Login" right from the console shell prompt and tell me what you see?

**Comment by markusmeyerhofer** [comment] 2018-09-20 23:40
Well... the app starts, but the screen remains black. As observed previously. The loginwindow.service is still dead, so..

**Comment by markusmeyerhofer** [comment] 2018-09-20 23:40
Well... the app starts, but the screen remains black. As observed previously. The loginwindow.service is still dead, so..
Sorry, accidentally clicked close...

**Comment by trunkmaster** [comment] 2018-09-20 23:45
Sorry, I have no more ideas. Could I have a SSH connection to the system with NextSpace (I guess it's VM)? Maybe screen sharing with Skype? It's hard to guess what the root cause of a problem...

**Comment by markusmeyerhofer** [comment] 2018-09-20 23:53
I got an ssh account added. How can I reach you for credentials?

**Comment by trunkmaster** [comment] 2018-09-20 23:55
Skype is OK? My nick is sssstoyan.

**Comment by trunkmaster** [comment] 2018-09-21 07:31
Thank you for your cooperation. Closing issue.

**Closed by trunkmaster** 2018-09-21 07:31 UTC

**Comment by trunkmaster** [comment] 2018-09-21 09:04
For the record: GNUstep back was compiled with "xlib" backend due to not installed libart_lgpl-devel package.
