### ISSUE TITLE
Error building Frameworks - undeclared identifier 'NSPasteboardTypeString'

### ISSUE THREAD

**Issue by hezi** [trunkmaster/nextspace#243] opened 2020-03-08 17:29 UTC
I'm trying to build nextspace by following the instructions at: 
https://github.com/trunkmaster/nextspace/wiki/Build-Guide

I fail to build `Frameworks`, due to the following error in `DesktopKit`

```
Making all for framework DesktopKit...
 Compiling file NXTIconLabel.m ...
NXTIconLabel.m:150:61: error: use of undeclared identifier 'NSPasteboardTypeString'
  pString = [[NSPasteboard generalPasteboard] stringForType:NSPasteboardTypeString];
                                                            ^
1 error generated.
```

I've checked the header files in `/Developer/Headers/AppKit/NSPasteboard.h` and it doesn't contain the missing symbol. Same goes for the header file in the gnustep version bundled with nextspace. (I did notice https://github.com/gnustep/libs-gui/blob/master/Headers/AppKit/NSPasteboard.h does contain it)

Any idea on what to do next? should I be using a newer gnustep version?

Thanks :)

**Comment by trunkmaster** [comment] 2020-03-08 22:21
Yes, current master branch developed against latest master branch of GNUstep. I've spend a couple of months committing to GNUstep libraries. The Build Guide is out of date for the moment. Sorry, I'll fix it later.

**Comment by armm77** [comment] 2020-03-09 00:44
hi @trunkmaster, the problem is that the wiki was made with version 0.25 of lib-gui, and the implementation of NSPasteboardTypeString was made in version 0.27.0 of the lib-gui, and with all the improvements you have made, the wiki and tar.gz are outdated.

https://github.com/trunkmaster/nextspace/commit/6bf5eabac3072fa01c076197e7f5782cadfbea77#r37413522

**Comment by trunkmaster** [comment] 2020-03-09 01:00
@armm77, I know. Future NEXTSPACE release will be based on master or some release branch of GNUstep with couple of my patches (I've mentioned some of them on https://trunkmaster.github.io).

**Comment by armm77** [comment] 2020-03-09 01:37
@trunkmaster, I know, your blog is interesting, I congratulate you for taking some time to place the progress and keep us updated with the new changes, I only comment where the error is found to minimize the incidents that open and we are all informed.

**Comment by hezi** [comment] 2020-03-09 10:48
Thanks @trunkmaster @armm77 - I could probably update the wiki page later today after I get back from work and successfully build.

**Comment by armm77** [comment] 2020-03-13 01:11
hi @hezi, this is solved following the steps for the compilation that @trunkmaster provided us.
https://github.com/trunkmaster/nextspace/issues/245

**Comment by trunkmaster** [comment] 2020-06-24 23:28
@hezi with latest 0.90 release this issue should be fixed.

**Comment by trunkmaster** [comment] 2020-08-10 22:42
@hezi I'm going to close this issue since it's fixed and no actions from March. Please reopen this issue if you need.

**Closed by trunkmaster** 2020-08-10 22:42 UTC
Labels: bug, feedback needed, fixed
