### ISSUE TITLE
[0.85] update install instructions with users directory

### ISSUE THREAD

**Issue by zeroheure** [trunkmaster/nextspace#218] opened 2019-05-26 13:20 UTC
Can't login into Nextspace. Console login works. New Centos 7 install in virtual machine, with your 0.85 RPM packages (without additional Gnustep packages).

Here's extract from error messages :

_gpbs  "unable to register with name server"_
I've checked that the hostname is in /etc/hosts

_gnustep-services EXITED with code 0_

_Workspace can't find user Gnustep directory_
no ~/Library folder
wmaker complains that wmaker.inst should be run

**Comment by zeroheure** [comment] 2019-05-26 13:38
Solved : 
user directory must be in /Users, not in /home. please add instructions.

**Comment by armm77** [comment] 2019-05-26 14:44
hi @zeroheure , a question followed the steps of the installation wiki.? although you have to update the wiki for the version 0.85, if it works, do not follow all the steps if you're just going to try the desktop.

[Build and install](https://github.com/trunkmaster/nextspace/wiki/Build-and-install)

###### I leave the history of the steps that worked for me.

> [root@nextspace ~]# history
>   1  yum update -y
>   2  reboot
>   3  yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
>   4  yum update -y
>   5  yum install -y nano
>   6  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/llvm-libs-7.0.1-3.el7.x86_64.rpm
>   7  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/clang-libs-7.0.1-4.el7.x86_64.rpm
>   8  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/clang-7.0.1-4.el7.x86_64.rpm
>   9  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/libdispatch-1.3.1121-3.el7.x86_64.rpm
>  10  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/libdispatch-devel-1.3.1121-3.el7.x86_64.rpm
>  11  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/libobjc2-2.0-3.el7.x86_64.rpm
>  12  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/libobjc2-devel-2.0-3.el7.x86_64.rpm
>  13  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-gnustep-1.26.0_0.25.0-2.el7.x86_64.rpm
>  14  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-gnustep-devel-1.26.0_0.25.0-2.el7.x86_64.rpm
>  15  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-frameworks-0.85-1.el7.x86_64.rpm
>  16  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-frameworks-devel-0.85-1.el7.x86_64.rpm
>  17  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-0.95-3.el7.x86_64.rpm
>  18  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-devel-0.95-3.el7.x86_64.rpm
>  19  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-applications-0.85-1.el7.x86_64.rpm
>  20  yum install -y https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-applications-devel-0.85-1.el7.x86_64.rpm
>  21  adduser -s /bin/zsh me
>  22  passwd me
>  23  ldconfig
>  24  nano /etc/sysconfig/selinux
>  25  nano /etc/hosts
>  26  reboot

**Comment by zeroheure** [comment] 2019-05-26 15:46
@armm77 yes I followed that steps too. But I didn't expected that the user created during Centos installation couldn't login to Nextspace.
BTW you don't need the adduser shell option, it's already in skel.

**Comment by armm77** [comment] 2019-05-26 21:19
> BTW you don't need the adduser shell option, it's already in skel.

It is necessary to create the user "me" because it does not exist.

**Comment by zeroheure** [comment] 2019-05-27 10:13
@armm77 sure but the shell option (-s /bin/zsh) is not necessasy

**Comment by trunkmaster** [comment] 2019-05-27 18:41
Guys, thank you for feedback. I’ve not finished testing yet. And I’m a bit offline for a week. I’ll plan to create two separate wiki pages: first for users and second for developers. There are a lot of changes since 0.85...

Sergii Stoian

**Comment by zeroheure** [comment] 2019-05-28 10:05
Keybord setup during Centos install was not there in Nextspace (but was in login.app)

**Comment by trunkmaster** [comment] 2019-05-28 12:48
It’s better to create new for keyboard setup. Keyboard setup made in CentOS ignored by NextSpace, right?

**Comment by zeroheure** [comment] 2019-05-28 13:03
yes

**Comment by trunkmaster** [comment] 2019-06-04 21:52
> @armm77 sure but the shell option (-s /bin/zsh) is not necessasy

This options is necessary because default shell is specified in `/etc/default/useradd` that out of control of NextSpace packages.

**Comment by trunkmaster** [comment] 2019-06-05 22:35
> yes

I've created new issue #220.

**Comment by paddle-to-the-sea** [comment] 2019-06-06 15:30
> @armm77 sure but the shell option (-s /bin/zsh) is not necessasy

@armm77 @zeroheure The `-s /bin/zsh` option is in the wiki install instructions due to #129. Basically, if you want to run the `patch` commands as given in [section 3.5 of the wiki Build and Install Guide](https://github.com/trunkmaster/nextspace/wiki/Build-and-install#3-build-nextspace), you need to be running `zsh`, not `bash`.

As far as I know, you are absolutely correct that if you are just installing RPMs, it is unnecessary to have the `-s /bin/zsh` option.

**Comment by zeroheure** [comment] 2019-06-06 16:19
So, to install RPM or to create user `-s /bin/zsh` option is unnecessary.
Thankyou, I was a bit worried that as a sysadmin I didn't understood well the man pages ! :-)

**Comment by paddle-to-the-sea** [comment] 2019-06-06 17:44
Thank you for pointing this out. The NEXTSPACE RPMs changing `/etc/skel` (or is it `/etc/default/useradd`?) to make `zsh` the default must be a change since the wiki was last updated.

In any event, @trunkmaster says above that he'll be modifying the wiki a lot in the near future, so I'm sure the updated docs will reflect all of this. (:

**Comment by zeroheure** [comment] 2019-06-06 18:29
You're right, it's obviously set in `/etc/default/useradd`

**Comment by trunkmaster** [comment] 2019-06-06 19:51
Guys, I think `-s /bin/zsh` is not harmful option. Yes, `/etc/default/useradd` is changed by 'nextspace-core' RPM on install, but this file can be changed by `shadow-utils`RPM update. 

The most appropriate way to install NEXTSPACE is described in wiki page. However, if you omitted to run `yum update` but have already installed NEXTSPACE RPMs and decide to run it - `/etc/default/useradd` will be overwritten by `shadow-utils` update.

Do you see any side effects of `-s /bin/zsh` option to `useradd`?

**Comment by zeroheure** [comment] 2019-06-06 20:01
There is no side effects with `-s /bin/zsh` option.

**Comment by trunkmaster** [comment] 2019-06-07 23:27
@zeroheure, @armm77 

Finally, 0.85 release with  ["Install Guide"](https://github.com/trunkmaster/nextspace/wiki/Install-Guide) and ["Build Guide" ](https://github.com/trunkmaster/nextspace/wiki/Build-Guide) is here.

Please check it, test it and let me know about results.

**Comment by zeroheure** [comment] 2019-06-08 13:11
Tested on virtual machine with 2 CPU, Ram 1024, hostname localhost.localdomain (left unchanged).

- in Install guide, the #3 `yum -y upgrade` does nothing because `yum -y update` have already done the job.
- "el7" is read as "e17". Compare : `el7` et `e17`, please add a note

First and next login attempt failure :
- user was created in /Users
- but at first login "WorkspaceManager quit with error" (gnustep-services exited with code 0, workspace exited with code 127)
- then, clicking on Power button results in login Window displaying "Restarting computer..." but nothing more 
- `systemctl stop loginwindow` freeze the system

After manual Poweroff, restart
- can't see if Plymouth theme works. What is it supposed to display ?

**Comment by armm77** [comment] 2019-06-08 14:15
@zeroheure, you can run ldconfig and try to enter, also present those incidents. 

I would also like you to try the audio I feel that a minimum configuration is missing for it to work.

**Comment by trunkmaster** [comment] 2019-06-09 12:35
> Tested on virtual machine with 2 CPU, Ram 1024, hostname localhost.localdomain (left unchanged).
>     * in Install guide, the #3 `yum -y upgrade` does nothing because `yum -y update` have already done the job.
Thanks. Fixed.

>     * "el7" is read as "e17". Compare : `el7` et `e17`, please add a note
I wrote "Install Guide" to be simple to make copy/paste commands. You can make CentOS install in VM, configure network access for VM, login with SSH from host system and copy/paste command from guide. Note that VM configuration, SSH installation out of scope of "Install Guide".

> First login attempt failure :
>     * user was created in /Users
>     * but at login "WorkspaceManager quit with error" (gnustep-services exited with code 0, workspace exited with code 127)
>     * then, clicking on Power button results in login Window displaying "Restarting computer..." but nothing more
>     * `systemctl stop loginwindow` freeze the system
Could you please show me the contents of your console.log? It's located in /tmp/GNUstepSecure<UID>/console.log, where UID is a ID of user created (by default it should be 1000).
Also I need to double-check installation process.

> After manual Poweroff, restart
>     * can't see if Plymouth theme works. What is it supposed to display ?
You should see login panel with text "System is coming up...". What is the output of `plymouth-set-default-theme`? What virtualization software are you using?

>     * login still not working
>     * power button works on loginwindow

**Comment by zeroheure** [comment] 2019-06-09 14:38
> I wrote "Install Guide" to be simple to make copy/paste commands.

Sure, but adding a litte note under "Install NextSpace" is not a big deal. Something like 
_`el7` below should be read "e L seven" not "e ONE seven"_

**Comment by zeroheure** [comment] 2019-06-09 14:47
> Note that VM configuration, SSH installation out of scope of "Install Guide".

And it's better like that. The more instructions you add, the more it confuse users.

**Comment by zeroheure** [comment] 2019-06-09 15:04
Here's console.log, but today only :

`2019-06-09 16:53:39.728 gdnc[3650:3650] NSUserDefaults file lock at <NSDistributedLock: 0x27af528> path '/Users/solariel/Library/Preferences/.lck/.GNUstepDefaults.lck' not locked is dated 2019-06-09 16:47:48 +0200 ... break
/usr/NextSpace/Apps/Workspace.app/Workspace: error while loading shared libraries: libWUtil.so.5: cannot open shared object file: No such file or directory
Stopping GNUstep services: gpbs gdnc.`

Plymouth default theme is `nextspace`.
I use Qemu with Spice display. While booting there is a white line at the bottom of the screen that became purple.
Lanching without Spice in a Qemu window (VGA output) does the same.

**Comment by trunkmaster** [comment] 2019-06-09 18:04
> Here's console.log, but today only :
> 
> `2019-06-09 16:53:39.728 gdnc[3650:3650] NSUserDefaults file lock at <NSDistributedLock: 0x27af528> path '/Users/solariel/Library/Preferences/.lck/.GNUstepDefaults.lck' not locked is dated 2019-06-09 16:47:48 +0200 ... break /usr/NextSpace/Apps/Workspace.app/Workspace: error while loading shared libraries: libWUtil.so.5: cannot open shared object file: No such file or directory Stopping GNUstep services: gpbs gdnc.`

It is problem with linker cache. I'l need to check installation from scratch.

> Plymouth default theme is `nextspace`.
> I use Qemu with Spice display. While booting there is a white line at the bottom of the screen that became purple.
> Lanching without Spice in a Qemu window (VGA output) does the same.

I'm not familiar with Qemu. I use VirtualBox. Current version (6.0) provides VMSVGA support and Linux has `vmwgfx` driver (included in initrd).
What KMS-compatible Linux driver supports Spice? I don't know.

**Comment by trunkmaster** [comment] 2019-06-09 18:05
@armm77 
> I would also like you to try the audio I feel that a minimum configuration is missing for it to work.

What do you mean? Could you be more specific?

**Comment by armm77** [comment] 2019-06-09 18:40
hi @trunkmaster, After the installation, I see that the audio does not work and it blocks the Preferences, it only happens when I start the session from the beginning of session, but when I start from GDM the audio works correctly.

I'm working with VMware Fusion and right now I'm doing the installation in Virtualbox

**Comment by zeroheure** [comment] 2019-06-09 20:07
Spice is a protocol from RedHat for remote access to virtual machines. It use the QXL video driver.

**Comment by trunkmaster** [comment] 2019-06-09 20:32
I'm not sure if Spice is applicable to use with graphics at boot.

**Comment by trunkmaster** [comment] 2019-06-09 20:35
@armm77, maybe there's some problem establish connection of "Sound Preferences" to PulseAudio server. Do you see controls after clicking on sound icon? What text do you see at the bottom of Preferences window after "Sound Preferences" are loaded?

**Comment by armm77** [comment] 2019-06-09 21:10
I logged in from Login and executed the pacmd list-cards command.
0 card(s) available.

And when I log in with GDM if I see the list of cards

![Screen Shot 2019-06-09 at 3 54 24 PM](https://user-images.githubusercontent.com/3104815/59164151-f2a05280-8ace-11e9-9d3b-cd2c2ddf21fb.png)

**Comment by trunkmaster** [comment] 2019-06-09 21:34
I guess I know where the problem is. Try to add your user to groups: `usermod -a -G audio,dbus <username>`. Logout, login. "Sound Preferences" should display ports and profiles. Tell me about results.

**Comment by armm77** [comment] 2019-06-09 21:57
@trunkmaster, if it worked for me, I just had to restart the vm and in the first attempt to reproduce the sound the Preferences are closed immediately, but then it works fine. 👍

**Comment by trunkmaster** [comment] 2019-06-09 22:07
I've added change to user creating in "Install Guide".

**Comment by trunkmaster** [comment] 2019-06-09 22:22
@zeroheure, to see graphical boot screen try to run `plymouth-set-default-theme -R nextspace` as root and reboot. I need to find where Plymouth boot screen configuration changes.

**Comment by zeroheure** [comment] 2019-06-10 22:21
I've redone a clean, complete install, following your instructions. The only difference was that I've created a user while installing Centos. And ... it works! at least I can log-in. But Nothing can be launch and Preferences window and Workspace window, while both apps are running, are not shown.

Here's Console log :
--------------------------------------
```
[Workspace] === Starting Workspace []... ===
[Workspace] === Initializing Window Manager... ===
2019-06-11 01:14:14.936 Workspace[16139:16139] OSEScreen: Apply automatic default display layout
2019-06-11 01:14:14.936 Workspace[16139:16139] Virtual-0: become main display.
2019-06-11 01:14:14.936 Workspace[16139:16139] Virtual-0: Set resolution {width = 1024; height = 768} and origin {x = 0; y = 0}
/bin/sh: wmsetbg : commande introuvable
[WM] will manage window:2097153
[WM] will manage window:2097155
[WM] will manage window:2097157
[WM] will manage window:2097168
[WM] will manage window:4194371
[WM] will manage window:4194537
[WM] will manage window:4194677
[WM] will manage window:4194678
[WM] will manage window:4194679
[WM] will manage window:4194745
[WM] will manage window:4194749
[WM] will manage window:4194762
[WM] will manage window:4194766
[WM] will manage window:4194770
[WM] will manage window:4194774
[WM] will manage window:4194778
[WM] will manage window:4194754
[WM] will manage window:4194758
2019-06-11 01:14:15.022 Workspace[16139:16139] Recycler: attach
2019-06-11 01:14:15.022 Workspace[16139:16139] XRRScreenChangeNotify received, updating applications and WindowMaker...
[Workspace] === Windoww Manager initialized! ===
[Workspace] === Starting Workspace application... ===
/usr/NextSpace/Apps/Workspace.app/Workspace(handle_inotify_events(WM/src/event.c:382)): warning: Inotify: Reading config files in defaults database.
2019-06-11 01:14:15.061 Workspace[16139:16139] styleoffsets ... guessing offsets
2019-06-11 01:14:15.061 Workspace[16139:16139] styleoffsets ... guessing offsets
[WM] Dock iconMouseDown
[WM] Dock iconMouseDown
2019-06-11 01:15:55.730 Preferences[16146:16146] styleoffsets ... guessing offsets
2019-06-11 01:15:55.730 Preferences[16146:16146] styleoffsets ... guessing offsets
[WM] will manage window:8388630
[WM wApplication] CREATE for window: 8388630 level:20 name: Preferences
[WM wApplication] ADD window: 8388630 level:20 name: Preferences refcount=1
```

**Comment by zeroheure** [comment] 2019-06-10 22:33
Some minor problems 
- after playing all the sounds, Preferences start consuming all CPU (but load < 1)
- keyboard selection is lost and can't be changed

**Comment by zeroheure** [comment] 2019-06-10 22:38
It is really really pleasant to use NextSpace. What a nice job you have done !

**Comment by trunkmaster** [comment] 2019-06-10 22:38
Do you see "File Viewer" window after logon?
I guess it's problem with first launch of GNUstep Pasteboard Service daemon (gpbs). After manually killing Workspace (`killall Workspace`) and login again - everything should work as expected.

**Comment by zeroheure** [comment] 2019-06-10 22:39
No the File Viewer was not shown. As I said, reboot solve the issue.

**Comment by trunkmaster** [comment] 2019-06-10 22:42
> No the File Viewer was not shown. As I said, reboot solve the issue. I can quickly test tomorow as I run only copy of my virtual machine.

It's definitely problem with `gpbs`.

> Time to sleep for me.

Good night. :)

**Comment by trunkmaster** [comment] 2019-06-11 07:58
@zeroheure,
I've updated nextspace-core package with changed defaults. You can test new behaviour performing the following steps:
1. Install update: `yum -y install https://github.com/trunkmaster/nextspace/releases/download/0.85/nextspace-core-0.95-7.el7.x86_64.rpm`
2. Remove user with home directory: `userdel -r <username>`
3. Remove GNUstep temporary directory: `rm -rf /tmp/GNUstepSecure<UID>`
4. Add user according to the "Install Guide".
5. Login and tell me about results.

**Comment by zeroheure** [comment] 2019-06-11 13:13
Works fine !
File viewer opens in browser mode at user's home directory. Don't you think it will help to understand system organisation if it open as before : in icon mode at Applications directory ?

**Comment by zeroheure** [comment] 2019-06-11 13:13
BTW PowerOff in workspace doesn't work.

**Comment by trunkmaster** [comment] 2019-06-11 15:18
> 
> 
> BTW PowerOff in workspace doesn't work.

I know, interconnection between Workspace and Login doesn't implemented yet.

**Comment by trunkmaster** [comment] 2019-06-11 15:30
> Don't you think it will help to understand system organisation if it open as before : in icon mode at Applications directory ?

"as before" - do you mean "as in MacOS"? Default behaviour of Workspace is to open File Viewer in home directory. But it remembers the last opened directory in root File Viewer (File Viewer without close button) and all opened other File Viewers with their path selections.

**Comment by zeroheure** [comment] 2019-06-11 16:15
"as before" mean I thought it was like that on my previous install :-)
File viewer opening in Applications with icon mode could help users (for the first launch only).

**Comment by trunkmaster** [comment] 2019-06-11 22:48
@zeroheure, maybe it's a good idea. Please create separate issue. I'm closing this.

**Closed by trunkmaster** 2019-06-11 22:48 UTC
Labels: bug
