### ISSUE TITLE
Linking tool FileMover.tool ...

### ISSUE THREAD

**Issue by armm77** [trunkmaster/nextspace#5] opened 2017-11-29 15:11 UTC
hello I'm having the following problem when compiling Applications

Making all in Preferences/BrowserPrefs ...
Making all for bundle BrowserPrefs...
gmake[5]: Nothing to be done for `internal-bundle-compile'.
 Copying localized resources into the bundle wrapper...
Making all in Tools/FileMover ...
Making all for tool FileMover.tool...
 Linking tool FileMover.tool ...
/usr/NextSpace/lib/libNXSystem.so: undefined reference to `GSCurrentServer'
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[5]: *** [obj/FileMover.tool] Error 1
gmake[4]: *** [internal-tool-all_] Error 2
gmake[3]: *** [FileMover.tool.all.tool.variables] Error 2
gmake[2]: *** [internal-all] Error 2
gmake[1]: *** [internal-all] Error 2
make: *** [internal-all] Error 2

**Comment by BertrandDekoninck** [comment] 2017-11-29 15:38
Same error here in a clean Centos VM after having installed  the Released rpms and  built  the frameworks.

**Comment by armm77** [comment] 2017-11-29 16:52
Thanks, I already did what you suggested but can not solve the error.
I have the same case that @BertrandDekoninck reports. I did the installation in a clean virtual machine with Centos 7 and the latest updates..

**Comment by trunkmaster** [comment] 2017-11-29 19:07
It's strange. Can you share output of 'make messages=yes'?

**Comment by armm77** [comment] 2017-11-29 19:47
Here is a detailed message of the make.
https://www.dropbox.com/s/8a842yp4us1uong/make-log?dl=0

**Comment by trunkmaster** [comment] 2017-11-29 21:10
OK, I'm preparing clean CentOS installation to check it. Meanwhile could you try to disable selinux (instructions here https://www.centos.org/docs/5/html/5.1/Deployment_Guide/sec-sel-enable-disable.html) and try compilation again?

**Comment by BertrandDekoninck** [comment] 2017-11-29 21:11
SELinux is disabled in mine.

**Comment by armm77** [comment] 2017-11-29 21:18
I deactivated selinux and went back to compile everything again but it follows the same error message.

**Comment by trunkmaster** [comment] 2017-11-29 21:21
OK, hold on.

**Comment by trunkmaster** [comment] 2017-11-29 21:28
@BertrandDekoninck, did you install NXAppKit with my changes to GNUmakefile.postamble?

**Comment by trunkmaster** [comment] 2017-11-29 21:32
Bad news guys... I've installed Minimal version of CentOS, install epel-release package with yum, install all RPMs from release. 'systemctl status gdomap' shows green light. It means - works for me.
@armm77, what status of 'gdomap' does 'systemctl' show on your system?

**Comment by BertrandDekoninck** [comment] 2017-11-29 21:54
I just reclone your repo (because I had some conflicts with the two last commits when running git fetch, strange), rebuild and install NX frameworks. And then, I wonder why, It tried to launch gdomap : fails. Then I did sudo ldconfig and rerun gdomap : success. Does gdomap in any manner need your framework to be properly installed ?

**Comment by trunkmaster** [comment] 2017-11-29 21:58
Of course, not. If you inspect log file you may find traces of problem. I think it's system's linker side effect.

**Comment by trunkmaster** [comment] 2017-11-29 22:05
@armm77, your original issue confirmed. I have the same error. I've gone digging.

**Comment by trunkmaster** [comment] 2017-11-29 22:50
Fixed in master branch. Pull, try to compile again and let me know the result.

**Comment by BertrandDekoninck** [comment] 2017-11-30 00:47
Applied. Everything builds fine. I could launch Workspace as a standalone app. It looks great. I didn't managed to lauch windowmaker session. How to do this ? I suppose I have to stop the gdm service because it doesn't offer anything but Gnome as Desktop Environnement. But then ? How do I launch Login.app ?

**Comment by trunkmaster** [comment] 2017-11-30 00:57
Yes, I've not created session file for GDM. Should I? Making clean install I've found one more bug... So if you want to start Login.app do the following: 
Create user to copy all necessary files into his home dir from /etc/skel and setup password for him.
# mkdir /usr/NextSpace/Preferences
# cp /usr/NextSpace/Apps/Login.app/Resources/Login /usr/NextSpace/Preferences
# systemctl start loginwindow
Login as created user.
Be aware that there is no WindowMaker session. If you run Workspace you've ran WindowMaker too. It is one application.

**Comment by BertrandDekoninck** [comment] 2017-11-30 01:22
I've done this.
I copied this "Login" file to /usr/NextSpace/Preferences.
systemctl fails to start Login, because it can't find the loginwindow.service file.
So I copied this file from Login.app ressource directoy to /etc/systemd/system (Yeah, my first tweak with systemd services).
Then I can launch Login, type my name and password, but Login shrinks (as in Nextstep !) and comes  back without launching Workspace. Gasp I give for tonight !

**Comment by BertrandDekoninck** [comment] 2017-11-30 01:23
Edit : I give up for tonight.

**Comment by armm77** [comment] 2017-11-30 04:10
I could not make Login.app work, but install lightdm and add a session that makes a call to the Workspace, everything works fine. Thanks for the help. 👍 :)

**Comment by trunkmaster** [comment] 2017-11-30 08:02
@BertrandDekoninck you need to check if user home directory has .xinitrc file. You can grab copy from /etc/skel dir. I know, onboarding is not perferct now. I just didn't test it well.

**Comment by trunkmaster** [comment] 2017-11-30 08:41
@armm77, I'm glad I've got a success. I hope next time it will be easier. Closing issue.

**Closed by trunkmaster** 2017-11-30 08:41 UTC
Labels: bug, question
